Model/employee
rutujanirmal/selecting_roommate pull request #1
Opened 2022-09-20 06:35 UTC by rutujanirmal

2022-09-20 06:55 UTC, niharikabhoi2020 commented on db/migrate/20220920061443_create_employees.rb
> +      t.string :email
email should be present true and unique

2022-09-20 06:57 UTC, niharikabhoi2020 requested changes

2022-09-20 06:57 UTC, niharikabhoi2020 commented on db/migrate/20220920061443_create_employees.rb
> +      t.integer :role , default: 0
use role as string. It will be easy to maintain and use

2022-09-20 06:57 UTC, niharikabhoi2020 commented on app/models/employee.rb
> +    "admin": 0
both keys have same value.

2022-09-20 06:57 UTC, niharikabhoi2020 commented on config/initializers/constants.rb
> +GENDER_REGEX = /^(M|F)$/
add new line at the end

2022-09-21 17:51 UTC, rutujanirmal commented
Changed employee to user model after discussion and raised another PR for the same

2022-09-21 17:51 UTC, closed without merging